# Introduction to sklearn/scikit-learn

In [1]:
from sklearn.datasets import load_wine
wine_data = load_wine()
wine_data.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]], shape=(178, 13))

In [2]:
import pandas as pd
from sklearn.datasets import load_wine

wine_data = load_wine()

# Convert data to pandas dataframe
wine_df = pd.DataFrame(wine_data.data, columns=wine_data.feature_names)

# Add the target label
wine_df["target"] = wine_data.target

# Take a preview
wine_df.head()
#wine_df.shape
#wine_df.tail(3)

   alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline  target
0    14.23        1.71  2.43  ...                          3.92   1065.0       0
1    13.20        1.78  2.14  ...                          3.40   1050.0       0
2    13.16        2.36  2.67  ...                          3.17   1185.0       0
3    14.37        1.95  2.50  ...                          3.45   1480.0       0
4    13.24        2.59  2.87  ...                          2.93    735.0       0

[5 rows x 14 columns]

In [3]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import sklearn
print(sklearn.__version__)

1.8.0

In [4]:
import pandas as pd

# heart_disease = pd.read_csv("../data/heart-disease.csv") # load data from local directory
heart_disease = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/heart-disease.csv") # load data directly from URL (requires raw form on GitHub, source: https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/data/heart-disease.csv)
heart_disease.tail()
#heart_disease.shape

     age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
298   57    0   0       140   241    0  ...      1      0.2      1   0     3       0
299   45    1   3       110   264    0  ...      0      1.2      1   0     3       0
300   68    1   0       144   193    1  ...      0      3.4      1   2     3       0
301   57    1   0       130   131    0  ...      1      1.2      1   1     3       0
302   57    0   1       130   236    0  ...      0      0.0      1   1     2       0

[5 rows x 14 columns]

In [5]:
# Create X( all the features) and y (the target label)
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]
X.tail()

     age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
298   57    0   0       140   241  ...      1      0.2      1   0     3
299   45    1   3       110   264  ...      0      1.2      1   0     3
300   68    1   0       144   193  ...      0      3.4      1   2     3
301   57    1   0       130   131  ...      1      1.2      1   1     3
302   57    0   1       130   236  ...      0      0.0      1   1     2

[5 rows x 13 columns]

step 1 : Get The Data Ready

In [6]:
#Splitting the data into training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

Step 2: Choose the model and hyper-parameters

In [7]:
# Since we're working on a classification problem, we'll start with a RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [9]:
from sklearn.linear_model import LogisticRegression
regressor = LogisticRegression()
regressor.fit(X_train, y_train)

c:\Python\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Step 3: Fit the model to the data use it to make the prediction

In [ ]:
clf.fit(X=X_train, y=y_train)

RandomForestClassifier()

Step 4: Use the model to make prediction

In [ ]:
X_test.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
18,43,1,0,150,247,0,1,171,0,1.5,2,0,2
268,54,1,0,122,286,0,0,116,1,3.2,1,2,2
103,42,1,2,120,240,1,1,194,0,0.8,0,0,3
66,51,1,2,100,222,0,1,143,1,1.2,1,0,2
144,76,0,2,140,197,0,2,116,0,1.1,1,0,2

In [ ]:
X_train.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
258,62,0,0,150,244,0,1,154,1,1.4,1,0,2
119,46,0,0,138,243,0,0,152,1,0.0,1,0,2
178,43,1,0,120,177,0,0,120,1,2.5,1,0,3
27,51,1,2,110,175,0,1,123,0,0.6,2,0,2
196,46,1,2,150,231,0,1,147,0,3.6,1,0,2

In [ ]:
y_test.head()

18     1
268    0
103    1
66     1
144    1
Name: target, dtype: int64

In [ ]:
y.head(10)

0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
9    1
Name: target, dtype: int64

In [ ]:
# Predictions using test and train data
y_preds = clf.predict(X=X_test)

Step 4: Evaluate the model

In [ ]:
# Evaluate the Testing Model
train_acc = clf.score(X_train, y_train)
print(f"Train accuracy: {train_acc*100:.2f}%")

# test_acc = clf.score(X_test, y_test)
# print(f"Test accuracy: {test_acc*100:.2f}%")

Train accuracy: 100.00%

In [ ]:
# Evaluate the model on the test set
test_acc = clf.score(X=X_test, y=y_test)
print(f"The model's accuracy on the testing dataset is: {test_acc*100:.2f}%")

The model's accuracy on the testing dataset is: 78.69%

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score,ConfusionMatrixDisplay
print(classification_report(y_test,y_preds))

print(confusion_matrix(y_test,y_preds))

print(f"accuracy score:{accuracy_score(y_test,y_preds)*100:.2f}%")

              precision    recall  f1-score   support

           0       0.85      0.72      0.78        32
           1       0.74      0.86      0.79        29

    accuracy                           0.79        61
   macro avg       0.79      0.79      0.79        61
weighted avg       0.80      0.79      0.79        61

[[23  9]
 [ 4 25]]
accuracy score:78.69%

In [ ]:
# Try different numbers of estimators (trees)... (no cross-validation)
np.random.seed(42)
for i in range(100, 200, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on test set: {model.score(X_test, y_test) * 100:.2f}%")
    print("")

Trying model with 100 estimators...

Model accuracy on test set: 81.97%

Trying model with 110 estimators...
Model accuracy on test set: 81.97%

Trying model with 120 estimators...
Model accuracy on test set: 81.97%

Trying model with 130 estimators...
Model accuracy on test set: 80.33%

Trying model with 140 estimators...
Model accuracy on test set: 80.33%

Trying model with 150 estimators...
Model accuracy on test set: 78.69%

Trying model with 160 estimators...
Model accuracy on test set: 78.69%

Trying model with 170 estimators...
Model accuracy on test set: 81.97%

Trying model with 180 estimators...
Model accuracy on test set: 81.97%

Trying model with 190 estimators...
Model accuracy on test set: 80.33%

In [ ]:
from sklearn.model_selection import cross_val_score

np.random.seed(42)
for i in range(10,60,20):
    print(f"Tyring Model with {i} estimators")
    model =RandomForestClassifier(n_estimators=i).fit(X_train,y_train)

    # Measure model accuracy on test set with cross-validation
    model_score = model.score(X_test,y_test)
    print(f"Model accuracy on single test set:{model_score*100:.2f}%")

    # Measure the mean cross-validation score (accuracy) of the model with 3 folds
    cross_val_score_mean = cross_val_score(model,X,y,cv=5).mean()
    print(f"Mean cross-validation score (accuracy): {cross_val_score_mean*100:.2f}%")
    print("")

Tyring Model with 10 estimators
Model accuracy on single test set:78.69%
Mean cross-validation score (accuracy): 78.54%

Tyring Model with 30 estimators
Model accuracy on single test set:78.69%
Mean cross-validation score (accuracy): 82.16%

Tyring Model with 50 estimators
Model accuracy on single test set:83.61%
Mean cross-validation score (accuracy): 82.48%

In [ ]:
# Another way to do it with GridSearchCV...
np.random.seed(42)
from sklearn.model_selection import GridSearchCV

# Define the parameters to search over in dictionary form
# (these can be any of your target model's hyperparameters)
param_grid = {'n_estimators': [i for i in range(100, 200, 10)]}

# Setup the grid search
grid = GridSearchCV(estimator=RandomForestClassifier(),
                    param_grid=param_grid,
                    cv=5,
                    verbose=1)

# Fit the grid search to the data
grid.fit(X, y)

# Find the best parameters
print(f"The best parameter values are: {grid.best_params_}")
print(f"With a score of: {grid.best_score_*100:.2f}%")

Fitting 5 folds for each of 10 candidates, totalling 50 fits
The best parameter values are: {'n_estimators': 120}
With a score of: 82.82%

In [ ]:
# We can Export our model as well with best estimators
# Set the model to be the best estimator
clf = grid.best_estimator_
clf

RandomForestClassifier(n_estimators=120)

In [ ]:
clf.fit(X_train, y_train)
print(f"Best model score on single split of data :{clf.score(X_test,y_test)*100:.2f}%")

Best model score on single split of data :80.33%

In [ ]:
heart_disease.head()
heart_disease.target.value_counts()
#heart_disease.target.value_counts().plot(kind="bar")
heart_disease.notna().sum()
heart_disease.fillna(value="Missing")
heart_disease.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
# Picking Ml model for regression problem
# Get California Housing dataset
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
print(housing) # gets downloaded as dictionary

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]], shape=(20640, 8)), 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)), 'frame': None, 'target_names': ['MedHouseVal'], 'feature_names': ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude'], 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [ ]:
housing_df = pd.DataFrame(housing.data ,columns=housing.feature_names)
housing_df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [ ]:
housing_df.shape

(20640, 8)