In [3]:
import pandas as pd

# sample data
data ={
    "city":["Hyderabad","Bangalore","Chennai","Mumbai"],
    "price":[100,200,300,400],
}

df = pd.DataFrame(data)
df

        city  price
0  Hyderabad    100
1  Bangalore    200
2    Chennai    300
3     Mumbai    400

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["price_encoded"] = le.fit_transform(df["city"])
df

        city  price  city_encoded  price_encoded
0  Hyderabad    100             2              2
1  Bangalore    200             0              0
2    Chennai    300             1              1
3     Mumbai    400             3              3

In [6]:
pd.get_dummies(df['city'])

   Bangalore  Chennai  Hyderabad  Mumbai
0      False    False       True   False
1       True    False      False   False
2      False     True      False   False
3      False    False      False    True

Scaling

In [7]:
import pandas as pd
data={
    "Age":[25,30,35,40],
    "Salary":[50000,60000,70000,80000],
}
df = pd.DataFrame(data)
df

   Age  Salary
0   25   50000
1   30   60000
2   35   70000
3   40   80000

In [9]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [12]:
ss = StandardScaler()
df_scaled = ss.fit_transform(df)
pd.DataFrame(df_scaled, columns=df.columns)

        Age    Salary
0 -1.341641 -1.341641
1 -0.447214 -0.447214
2  0.447214  0.447214
3  1.341641  1.341641

In [13]:
ms = MinMaxScaler()
df_scaled= ms.fit_transform(df)
pd.DataFrame(df_scaled, columns=df.columns)

        Age    Salary
0  0.000000  0.000000
1  0.333333  0.333333
2  0.666667  0.666667
3  1.000000  1.000000