Import dataset

In [2]:
!kaggle datasets download -d ahmedgaitani/customer-churn-prediction-dataset

Dataset URL: https://www.kaggle.com/datasets/ahmedgaitani/customer-churn-prediction-dataset
License(s): CC0-1.0
customer-churn-prediction-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)

In [4]:
from zipfile import ZipFile
dataset = "D:\python\ML\pre_processing\customer-churn-prediction-dataset.zip"

with ZipFile(dataset, 'r') as zip:
  zip.extractall()
  print('The dataset is extracted')

The dataset is extracted

<>:2: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
<>:2: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
C:\Users\Rineeth\AppData\Local\Temp\ipykernel_40036\1397977876.py:2: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
  dataset = "D:\python\ML\pre_processing\customer-churn-prediction-dataset.zip"

In [5]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,root_mean_squared_error

In [8]:
data = pd.read_csv('D:\python\ML\pre_processing\customer_churn_prediction_dataset.csv')

<>:1: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
<>:1: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
C:\Users\Rineeth\AppData\Local\Temp\ipykernel_40036\2859280316.py:1: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
  data = pd.read_csv('D:\python\ML\pre_processing\customer_churn_prediction_dataset.csv')

In [9]:
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0001-XXXX,Male,0,Yes,Yes,5,No,Yes,No,No,...,No,No,No,No internet service,Month-to-month,Yes,Credit card,27.43,137.15,Yes
1,0002-XXXX,Female,0,No,No,42,Yes,No phone service,DSL,Yes,...,No,No,No internet service,No internet service,Two year,No,Electronic check,38.28,1607.76,Yes
2,0003-XXXX,Male,0,No,No,61,Yes,No phone service,No,No,...,No,Yes,Yes,No,One year,No,Bank transfer,106.44,6492.84,Yes
3,0004-XXXX,Male,1,No,Yes,22,Yes,No,No,No internet service,...,Yes,No,No internet service,Yes,Month-to-month,No,Electronic check,92.49,2034.78,No
4,0005-XXXX,Male,1,Yes,Yes,21,No,No,DSL,No,...,No internet service,No,No,No internet service,One year,No,Bank transfer,19.63,412.23,Yes

In [10]:
data.shape

(300, 21)

In [11]:
data.describe()

       SeniorCitizen      tenure  MonthlyCharges  TotalCharges
count     300.000000  300.000000      300.000000    300.000000
mean        0.543333   35.783333       67.226800   2477.975767
std         0.498951   21.113400       28.638073   1918.540111
min         0.000000    1.000000       18.450000     30.030000
25%         0.000000   17.000000       42.337500    910.302500
50%         1.000000   36.000000       68.635000   2072.400000
75%         1.000000   53.250000       92.430000   3618.405000
max         1.000000   72.000000      118.640000   8318.880000

In [12]:
data.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [14]:
# If there are missing values, we can handle them using imputation techniques. For numerical features, we can use mean or median imputation, and for categorical features, we can use the most frequent value.
data.fillna(data.mean(numeric_only=True), inplace=True)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0001-XXXX,Male,0,Yes,Yes,5,No,Yes,No,No,...,No,No,No,No internet service,Month-to-month,Yes,Credit card,27.43,137.15,Yes
1,0002-XXXX,Female,0,No,No,42,Yes,No phone service,DSL,Yes,...,No,No,No internet service,No internet service,Two year,No,Electronic check,38.28,1607.76,Yes
2,0003-XXXX,Male,0,No,No,61,Yes,No phone service,No,No,...,No,Yes,Yes,No,One year,No,Bank transfer,106.44,6492.84,Yes
3,0004-XXXX,Male,1,No,Yes,22,Yes,No,No,No internet service,...,Yes,No,No internet service,Yes,Month-to-month,No,Electronic check,92.49,2034.78,No
4,0005-XXXX,Male,1,Yes,Yes,21,No,No,DSL,No,...,No internet service,No,No,No internet service,One year,No,Bank transfer,19.63,412.23,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,0296-XXXX,Female,1,No,Yes,61,No,Yes,DSL,No,...,Yes,No internet service,No,No,One year,Yes,Electronic check,42.52,2593.72,No
296,0297-XXXX,Female,0,No,No,49,Yes,No phone service,DSL,No internet service,...,Yes,No internet service,Yes,Yes,Month-to-month,Yes,Mailed check,22.31,1093.19,Yes
297,0298-XXXX,Male,0,No,Yes,71,Yes,Yes,DSL,No internet service,...,Yes,Yes,No,Yes,Two year,No,Mailed check,59.57,4229.47,Yes
298,0299-XXXX,Male,1,Yes,Yes,1,Yes,Yes,No,Yes,...,No internet service,No internet service,Yes,Yes,Two year,No,Credit card,31.32,31.32,No
299,0300-XXXX,Female,1,Yes,Yes,13,Yes,Yes,DSL,No internet service,...,Yes,No,No internet service,Yes,Month-to-month,No,Electronic check,20.50,266.50,Yes

In [28]:
data.drop("customerID", axis=1, inplace=True)

In [29]:
# one-hot encoding
data = pd.get_dummies(data, drop_first=True)

In [16]:
# ML do not handle categorical data, so we need to encode the categorical features using one-hot encoding or label encoding. We can use the OneHotEncoder from scikit-learn to perform one-hot encoding on the categorical features.
categorical_features = data.select_dtypes(include=['object']).columns
numerical_features = data.select_dtypes(include=['int64', 'float64']).columns

C:\Users\Rineeth\AppData\Local\Temp\ipykernel_40036\1664110813.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = data.select_dtypes(include=['object']).columns

In [17]:
#Split the data into features and target variable
X = data.drop('Churn', axis=1)
y = data['Churn']

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train[numerical_features] = scaler.fit_transform(X_train[numerical_features])
X_test[numerical_features] = scaler.transform(X_test[numerical_features])

In [20]:
scaler.fit(X_train[numerical_features])

StandardScaler()

In [21]:
scaler.fit(X_test[numerical_features])

StandardScaler()

In [33]:
data.astype(str).apply(lambda col: col.str.contains("0233-XXXX", na=False)).any()

SeniorCitizen                           False
tenure                                  False
MonthlyCharges                          False
TotalCharges                            False
gender_Male                             False
Partner_Yes                             False
Dependents_Yes                          False
PhoneService_Yes                        False
MultipleLines_No phone service          False
MultipleLines_Yes                       False
InternetService_Fiber optic             False
InternetService_No                      False
OnlineSecurity_No internet service      False
OnlineSecurity_Yes                      False
OnlineBackup_No internet service        False
OnlineBackup_Yes                        False
DeviceProtection_No internet service    False
DeviceProtection_Yes                    False
TechSupport_No internet service         False
TechSupport_Yes                         False
StreamingTV_No internet service         False
StreamingTV_Yes                         False
StreamingMovies_No internet service     False
StreamingMovies_Yes                     False
Contract_One year                       False
Contract_Two year                       False
PaperlessBilling_Yes                    False
PaymentMethod_Credit card               False
PaymentMethod_Electronic check          False
PaymentMethod_Mailed check              False
Churn_Yes                               False
dtype: bool

In [36]:
print(data.info())
print(data.isnull().sum())
print(data.select_dtypes(include='object').columns)

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 31 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   SeniorCitizen                         300 non-null    int64
 1   tenure                                300 non-null    int64
 2   MonthlyCharges                        300 non-null    float64
 3   TotalCharges                          300 non-null    float64
 4   gender_Male                           300 non-null    bool
 5   Partner_Yes                           300 non-null    bool
 6   Dependents_Yes                        300 non-null    bool
 7   PhoneService_Yes                      300 non-null    bool
 8   MultipleLines_No phone service        300 non-null    bool
 9   MultipleLines_Yes                     300 non-null    bool
 10  InternetService_Fiber optic           300 non-null    bool
 11  InternetService_No                    300 non-null    bool
 12  OnlineSecurity_No internet service    300 non-null    bool
 13  OnlineSecurity_Yes                    300 non-null    bool
 14  OnlineBackup_No internet service      300 non-null    bool
 15  OnlineBackup_Yes                      300 non-null    bool
 16  DeviceProtection_No internet service  300 non-null    bool
 17  DeviceProtection_Yes                  300 non-null    bool
 18  TechSupport_No internet service       300 non-null    bool
 19  TechSupport_Yes                       300 non-null    bool
 20  StreamingTV_No internet service       300 non-null    bool
 21  StreamingTV_Yes                       300 non-null    bool
 22  StreamingMovies_No internet service   300 non-null    bool
 23  StreamingMovies_Yes                   300 non-null    bool
 24  Contract_One year                     300 non-null    bool
 25  Contract_Two year                     300 non-null    bool
 26  PaperlessBilling_Yes                  300 non-null    bool
 27  PaymentMethod_Credit card             300 non-null    bool
 28  PaymentMethod_Electronic check        300 non-null    bool
 29  PaymentMethod_Mailed check            300 non-null    bool
 30  Churn_Yes                             300 non-null    bool
dtypes: bool(27), float64(2), int64(2)
memory usage: 17.4 KB
None
SeniorCitizen                           0
tenure                                  0
MonthlyCharges                          0
TotalCharges                            0
gender_Male                             0
Partner_Yes                             0
Dependents_Yes                          0
PhoneService_Yes                        0
MultipleLines_No phone service          0
MultipleLines_Yes                       0
InternetService_Fiber optic             0
InternetService_No                      0
OnlineSecurity_No internet service      0
OnlineSecurity_Yes                      0
OnlineBackup_No internet service        0
OnlineBackup_Yes                        0
DeviceProtection_No internet service    0
DeviceProtection_Yes                    0
TechSupport_No internet service         0
TechSupport_Yes                         0
StreamingTV_No internet service         0
StreamingTV_Yes                         0
StreamingMovies_No internet service     0
StreamingMovies_Yes                     0
Contract_One year                       0
Contract_Two year                       0
PaperlessBilling_Yes                    0
PaymentMethod_Credit card               0
PaymentMethod_Electronic check          0
PaymentMethod_Mailed check              0
Churn_Yes                               0
dtype: int64
Index([], dtype='str')

In [37]:
print(data.select_dtypes(include='object').columns)

Index([], dtype='str')

In [42]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

df = pd.read_csv("customer_churn_prediction_dataset.csv")

# Drop ID column if present
df = df.drop(columns=["customerID"], errors="ignore")

# Separate input and output
X = df.drop("Churn", axis=1)   # change Churn if your target column name is different
y = df["Churn"]

# Convert Yes/No and other text columns into numbers
X = pd.get_dummies(X, drop_first=True)

# If target is Yes/No, convert it too
y = y.map({"No": 0, "Yes": 1})

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

c:\Users\Rineeth\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [43]:
X_train.select_dtypes(include="object").columns

Index([], dtype='str')