In [ ]:
# Merging Dataframes
import pandas as pd
df1 = pd.DataFrame({'id1':[1,2,3,4],'name':['Rineeth','kiran','Sunny','Trisha']})

df2 = pd.DataFrame({'id2':[3,4,5,6],'course':['Python','ML','Java','AI']})

inner_result = pd.merge(df1,df2, how='inner' , on='id')
inner_result

   id    name  course
0   3   Sunny  Python
1   4  Trisha      ML

In [2]:
outer_result = pd.merge(df1,df2, how='outer' , on='id')
outer_result

   id     name  course
0   1  Rineeth     NaN
1   2    kiran     NaN
2   3    Sunny  Python
3   4   Trisha      ML
4   5      NaN    Java
5   6      NaN      AI

In [3]:
left_result = pd.merge(df1,df2, how='left' , on='id')
left_result

   id     name  course
0   1  Rineeth     NaN
1   2    kiran     NaN
2   3    Sunny  Python
3   4   Trisha      ML

In [4]:
right_result = pd.merge(df1,df2, how='right' , on='id')
right_result

   id    name  course
0   3   Sunny  Python
1   4  Trisha      ML
2   5     NaN    Java
3   6     NaN      AI

In [6]:
result = pd.concat([df1,df2],axis=0, ignore_index=True)
result

   id     name  course
0   1  Rineeth     NaN
1   2    kiran     NaN
2   3    Sunny     NaN
3   4   Trisha     NaN
4   3      NaN  Python
5   4      NaN      ML
6   5      NaN    Java
7   6      NaN      AI

In [7]:
result = pd.concat([df1,df2],axis=1)
result

   id     name  id  course
0   1  Rineeth   3  Python
1   2    kiran   4      ML
2   3    Sunny   5    Java
3   4   Trisha   6      AI

In [8]:
result = pd.concat([df1,df2],axis=0, keys=['df1','df2'])
result

       id     name  course
df1 0   1  Rineeth     NaN
    1   2    kiran     NaN
    2   3    Sunny     NaN
    3   4   Trisha     NaN
df2 0   3      NaN  Python
    1   4      NaN      ML
    2   5      NaN    Java
    3   6      NaN      AI

In [9]:
result.isna()

          id   name  course
df1 0  False  False    True
    1  False  False    True
    2  False  False    True
    3  False  False    True
df2 0  False   True   False
    1  False   True   False
    2  False   True   False
    3  False   True   False

In [15]:
result.isna().sum()

id        0
name      4
course    4
dtype: int64

In [12]:
result.notna()

         id   name  course
df1 0  True   True   False
    1  True   True   False
    2  True   True   False
    3  True   True   False
df2 0  True  False    True
    1  True  False    True
    2  True  False    True
    3  True  False    True

In [13]:
result.notna().sum()

id        8
name      4
course    4
dtype: int64